# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff345a6a9c98a6d9a39217acedf0dae3c975ab052c4d814cf82762175a18bb27e0ed587c873099de16df13c01d2f571721cb320393693f4723e0fccbf224a64d

test:
  secret_key_base: 7a21bf3efd9457950f86993d990bfe21c55ed93ec373012215be7efc0e9a1b5e4d7fc985443f1e52ba8cb5e31ea0e0ca74fd116d52f4508f3566496ed78f9317

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
